-- VERALTET / FEHLERHAFT -- bitte nicht verwenden.
--
-- Diese Datei wurde durch den fehlerhaften ersten Phase-E-Commit (cd72a3f)
-- versehentlich als leerer Stub angelegt. Das GitHub-API-Loeschen dieser
-- Datei schlaegt aktuell mit einem internen Fehler (GitRPC::BadObjectState)
-- fehl, daher wird der Inhalt hier stattdessen durch diesen Hinweis ersetzt.
--
-- Das tatsaechliche, vollstaendige Datenbankschema befindet sich in:
--   docs/03_Datenbank_Schema_MySQL_MultiRallye_v4.sql
--
-- Die Phase-E-Erweiterungen (photo_ref, photo_submissions) sind in
-- backend/migrations/002_ermittler_chat_phase_e.sql sowie in
-- docs/06_Phase_E_Foto_Einreichung.md dokumentiert.
